### ISSUE TITLE
Orchestra Platform 2.1

### ISSUE THREAD

**Issue by crynobone** [orchestral/platform#13]
## Platform
- [x] Add a quick installation guide on Github.
- [x] Improve Orchestra Platform performance.
- [x] Include `orchestra/control` by default. #17 
- [x] Include `orchestra/story` by default. #18
- ~~Send email as text/html and text/plain. #25~~
- [x] Change minimum stability to stable.
#### Laravel Changes
- [x] Add **remote** support.
- [x] Support for `Illuminate\Routing` refactors.
- [x] Update default view for slider pagination to Bootstrap 3.
- [x] Setup live debugger in app.
- [x] Update controller alias.
- [x] Added repository to Composer file.
- [x] Include [upgrading guide](https://github.com/orchestral/platform/blob/master/docs/upgrading.md#upgrading-from-v20-to-v21).
### Asset
- [x] Add `Orchestra\Asset\Container::show()` method to compile both styles and scripts. orchestral/asset#3
### Auth
- [x] Predefined package path to avoid additional overhead to guest package path. orchestral/auth#15
- [x] Move commands to it's own service provider. orchestral/auth#16
- [x] Provide an easier method to override default auth.roles listener. orchestral/auth#19
### Debug
- ~~Add `Profiler::time()` and `Profiler::timeEnd()`. orchestral/debug#4~~
- [x] Allow framework agnostic compatibility. orchestral/debug#3
### Extension
- [x] Predefined package path to avoid additional overhead to guest package path. orchestral/extension#33
- [x] Move commands to it's own service provider. orchestral/extension#34
- [x] Allow wildcard {{domain}} for extension routing via Orchestra\Extension\RouteGenerator. orchestral/extension#35
- [x] Add Orchestra\Extension\RouteGenerator::is() helper. orchestral/extension#39
### Facile
- [x] Check request header to detect allowed content-type. orchestral/facile#3
- [x] Refactor private API to reduce redundant responsibility.
### Foundation
- [x] Predefined package path to avoid additional overhead to guest package path. orchestral/foundation#107
- [x] Allow AdminMenuHandler to be configurable. orchestral/foundation#56
- [x] Update support for Laravel 4.1 routing. orchestral/foundation#104
- [x] Only display resources in navigation menus if not hidden. orchestral/foundation#108
- ~~Send email as text/html and text/plain. orchestral/foundation#117~~
- [x] Update Password Reminder/Reset functionality based on changes in Laravel 4.1. orchestral/foundation#121
- [x] Allow event listener to listen to specific route/view composing. orchestral/foundation#126
- [x] Include `orchestra/debug` by default.
- [x] Include `orchestra/optimize`, allow to concat/compile Orchestra Platform frequently accessed files.
### Html
- [x] Predefined package path to avoid additional overhead to guest package path. orchestral/html#11
- [x] Add support for button from Form Builder.
- [x] Add `Orchestra\Html\Form\Grid::setup()` and `Orchestra\Html\Form\Grid::resource()` helper.
### Memory
- [x] Predefined package path to avoid additional overhead to guest package path. orchestral/memory#10
- [x] Move commands to it's own service provider. orchestral/memory#11
- [x] Implement a caching layer on top of Fluent and Eloquent driver. orchestral/memory#14
### Optimize
- [x] Update list of compiled classes for Orchestra Platform 2.1.
- [x] Replace default composer.json post commands.
- ~~Add orchestra/warden. orchestral/optimize#2~~
### Resources
- [x] Update support for Laravel 4.1 controller dispatching. orchestral/resources#8
### Support
- [x] Add `Orchestra\Support\Relic`.
- [x] Add `Orchestra\Support\Str::replace()`.
- [x] Add `Orchestra\Support\Facades\Warden` for `orchestra/warden` integration.
### Translation
- [x] Deprecated since `illuminate/translation` already offer the same functionality.
### Testbench
- [x] Update support for Laravel 4.1.
### View
- ~~Add `Orchestra\View\Theme\Container::map()` method, missing feature from Orchestra Platform 1. orchestral/view#7~~
- ~~Artisan Command for View. orchestral/view#12~~
### Warden
- ~~Add orchestra/warden component. orchestral/warden#1~~
### Widget
- [x] Predefined package path to avoid additional overhead to guest package path. orchestral/widget#6
## Website
- [x] Redevelop the website using Orchestra Platform.
