### ISSUE TITLE
Orchestra Platform 2.2

### ISSUE THREAD

**Issue by crynobone** [orchestral/platform#30]
- [x] Increase minimum PHP version to 5.4*
- [x] Add support to [Laravel Forge](http://forge.laravel.com) and Homestead. #38 
- [x] Add `SoftDeletingTrait` to the default `User` class.
### Asset
- [x] Add support for `Orchestra\Asset\Container::prefix()` to support external URL. orchestral/asset#7
### Auth
- [x] Add support for new remember_token.
- [x] Add `Orchestra\Auth\Acl\AuthorizationTrait`.
### Extension
- [x] Convert `php artisan extension:detect` to use Symfony's table.
### Facile
- [x] Allow output as CSV.
### Foundation
- [x] Add support for sending emails using mandrill and mailgun API. orchestral/foundation#152
- [x] Set `email_domain` and `email_secret` to value from config is null/empty. orchestral/foundation#153
### Notifier
- [x] Add mandrill and mailgun API transport. orchestral/notifier#4
- [x] Update code to match latest changes to Mail::send() return value to null for all transport. orchestral/notifier#6
### Support
- [x] Add `Orchestra\Support\Traits\ObservableTrait`.
- [x] Add `Orchestra\Support\Traits\QueryFilterTrait`.
- [x] Add `Orchestra\Support\Traits\UploadableTrait`.
- [x] Add `Orchestra\Support\Traits\ValidationTrait`.
### View
- [x] Command for managing theme options.

> \* We however will not accept massive array() to [] Pull Request until 2.1 reach End of Life (EOL) by January 15th, 2016.
