### ISSUE TITLE
[WIP] Orchestra Platform 3.0

### ISSUE THREAD

**Issue by crynobone** [orchestral/platform#42]
## Platform

* [x] Support for Laravel 5.0
* [x] Add `App\Providers\ExtensionServiceProvider` #43 
* [x] Add `App\Providers\DebugServiceProvider` d8b66d5
* [x] Include `orchestra/testbench` as default `TestCase`.
* [x] Improves default page.

### Auth

* [x] Rename `Orchestra\Auth\Acl\Container` to `Orchestra\Auth\Acl\Acl`.
* [x] Add auth contracts.

### Extension

* ~~Allow support for `"base"`'s `orchestra.json` and orchestra folder to `base_path().'/orchestra`.~~
* [x] Remove `Orchestra\Extension\PublisherServiceProvider`.
* [x] Allow to register deferred services. orchestral/extension@cb110a7
* [x] Add extension contracts.
* [x] Safe mode should persist between request. orchestral/extension#52

### Facile

* [x] Rename `Orchestra\Facile\Container` and `Orchestra\Facile\Facile`.
* [x] Rename template classes.

### Foundation

* [x] Include `base_path().'/database/orchestra/installer.php` for installation. orchestral/foundation#161
* [x] Update `Form` and `HTML` facades location.
* ~~Should be able to set configuration to allow caching of UserMetaRepository. orchestral/foundation#162~~
* [x] Add `Orchestra\Foundation\Providers\ExtensionServiceProvider`. orchestral/foundation#163
* [x] Implement filters and middleware for routing.
* [x] Fixes routing test suite.
* [x] Make installation routes optional.
* [x] Make `orchestra/debug` optional.
* [x] Make `orchestra/resources` optional.
* [x] Make `orchestra/facile` optional.
* [x] Use `Orchestra\Foundation\Middleware\UseBackendTheme` middleware. orchestral/foundation#169
* [x] Separate Routing and Processor test case. orchestral/foundation#168

### HTML

* [x] Explicitly require illuminate/html. orchestral/html#25
* [x] Allow `Orchestra\Html\Form\Factory` to handle all request to `Illuminate\Html\FormBuilder`.
* [x] Add `Orchestra\Html\Table\Grid::searchable()` and `Orchestra\Html\Table\Grid::sortable()` to facilitate searching and sorting.
* [x] Allow to retrieve instance of `Illuminate\Http\Request` and `Illuminate\Translation\Translator` from within Form and Table builder.
* [x] Add `Orchestra\Html\Table\Grid::paginated()` helper method to access pagination state for current table.
* [x] Allow support for `checkboxes` form.
* [x] Allow control to be accessed from `Orchestra\Html\Form\Grid` context via a new `find()` method.
* [x] Update `Illuminate\Pagination\Paginator` changes.

### Memory

* [x] Remove `Orchestra\Memory\Abstractable\Container`.
* [x] Change the way configuration is cached when using `Orchestra\Memory\Abstractable\DatabaseHandler`. orchestral/memory#19

### Model

* ~~Should be able to use caching with `Orchestra\Model\Memory\UserMetaRepository`. orchestral/model#11~~
* [x] Setup morph class name for User and Role model. orchestral/model#12
* [x] Use DI instead of Facade for RoleObserver. orchestral/model#13

### Optimize

* [x] Update changes to `Illuminate\Foundation\Console\OptimizeCommand`.
* [x] Update compiled list.

### Publisher

* [x] Config publishing command.
* ~~Migration publishing command.~~

### Resources

* [x] Use `orchestra/routing`.
* [x] Rename `Orchestra\Resources\Container` and `Orchestra\Resources\Router`.
* [x] Add `get()`, `set()` and `forget()` helper method on `Orchestra\Resources\Router` to allow direct manipulation to it's attributes value.

### Testbench

* [x] Update application bootstrap action to match Laravel 5.0
* [x] Update config templates to match Laravel 5.0

### Support

* [x] Add `Orchestra\Support\Facades\HTML` facade.
* [x] Remove `Orchestra\Support\Relic`.
* [x] Remove `Orchestra\Support\Messages`.
* [x] Remove `Orchestra\Support\MessagesServiceProvider`.

### View

* ~~Include `app_path().'/Http/Views` for default view path.~~
* [x] Allow cascading theme views replacement if available from `resources/themes/*` directory.
* ~~Elixir helper for theme. orchestral/view#16~~

### Control

* [x] Update `Form` and `HTML` facades location.
* [x] Register routing through `Illuminate\Routing\Router` instead of `Orchestra\Resources`. orchestral/control#26
* [x] Convert filter to class. orchestral/control#27
* [x] Create `Orchestra\Control\ControlMenuHandler`. orchestral/control#28

### Story CMS

* [x] Update `Form` and `HTML` facades location.
* [x] Register routing through `Illuminate\Routing\Router` instead of `Orchestra\Resources`. orchestral/story#41
* [x] Replace Markdown parser with Parsedown. orchestral/story#39
* [x] Setup morph class name for Content model. orchestral/story#40
* [ ]  Update to latest lepture editor. orchestral/story#42
* [x] Convert filter to class. orchestral/story#44
* [x] Create `Orchestra\Story\StoryMenuHandler`. orchestral/story#48

## Integrations

* [x] Properly handle `Illuminate\Http\Request` not available from within console environment.
* [x] Properly handle public path when using `php artisan serve`.

**Comment by rossedman** [comment]
:clap:
