### ISSUE TITLE
[WIP] Orchestra Platform v3.2.0

### ISSUE THREAD

**Issue by crynobone** [orchestral/platform#49]
We would love to get your feedback and ideas for Orchestra Platform 3.2. Just post them here.

The following lists are a short roundup of all feature requests below (hope I did not miss one) and what our thoughts are about them. I will update the list if new ideas are posted.

## Platform

* ~~Bump minimum requirement to PHP 5.6.0.~~

### Extension

* [x] Add support to allow configurable extension route caching. orchestral/extension#55
* [x] Retrieve version number directly from `composer.lock`. orchestral/extension#56
* [x] Allow to register extension service provider based on when() event. orchestral/extension#57
* [x] Remove less relevant data stored in memory. orchestral/extension#58
* [x] Simplified registering extension configuration via `Orchestra\Extension\Plugin`.

### Facile

* [x] Allow to get proper response based on `Accept` header (via content-negotiation). orchestral/facile#10

### Foundation

* [x] Remove default support to `orchestra/resources`. orchestral/foundation#187
* [x] Remove unmaintained `it` language files. orchestral/foundation@99aa686
* [x] Defer orchestra/foundation routes registration after extension has been loaded. orchestral/foundation#185
* [x] Allow safe mode to persist between request. orchestral/foundation#189
* [x] Remove `Orchestra\Foundation\AdminMenuHandler`. orchestral/foundation#191

### Imagine

* [x] Create dispatchable job that you can use to resize an image. orchestral/imagine#15

### Kernel

* [x] Remove deprecated route filters. orchestral/kernel@3ba34ed

### Support

* [x] `Orchestra\Support\Expression` should implements `Illuminate\Contracts\Support\Htmlable`. orchestral/support#39

### Testbench

* [x] Remove Behat. orchestral/testbench#95

**Comment by stewhouston** [comment]
Hi, I'm a bit rusty with Laravel and am brand new to Orchestra. I'm finding the documentation a bit lacking. I'm curious with the Resources extension, where exactly am I supposed to be including the Event::listen hook?

Similarly, I'd like to add several Widgets to the /admin homepage, but I'm not sure where I'm supposed to begin adding my code.

**Comment by crynobone** [comment]
> I'm curious with the Resources extension, where exactly am I supposed to be including the Event::listen hook?

You can stop using Resources extension (it has been marked as deprecated) and focus on <http://orchestraplatform.com/docs/3.1/routing>

> Similarly, I'd like to add several Widgets to the /admin homepage, but I'm not sure where I'm supposed to begin adding my code.

You could do it via View Composers (I recommend creating classes for it). <http://laravel.com/docs/5.1/views#view-composers>
